<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>ItemShareFix</AssemblyName>
    <RootNamespace>ItemShareFix</RootNamespace>
    <RiskOfRain2Dir Condition="'$(RiskOfRain2Dir)' == ''">$(ROR2_GAME_DIR)</RiskOfRain2Dir>
    <ManagedDir>$(RiskOfRain2Dir)/Risk of Rain 2_Data/Managed</ManagedDir>
    <BepInExCoreDir>$(RiskOfRain2Dir)/BepInEx/core</BepInExCoreDir>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ItemShareFix.Core/ItemShareFix.Core.csproj" />
    <Reference Include="BepInEx"><HintPath>$(BepInExCoreDir)/BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(BepInExCoreDir)/0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="RoR2"><HintPath>$(ManagedDir)/RoR2.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(ManagedDir)/UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(ManagedDir)/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UIModule"><HintPath>$(ManagedDir)/UnityEngine.UIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UI"><HintPath>$(ManagedDir)/UnityEngine.UI.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.TextMeshPro"><HintPath>$(ManagedDir)/Unity.TextMeshPro.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="com.unity.multiplayer-hlapi.Runtime"><HintPath>$(ManagedDir)/com.unity.multiplayer-hlapi.Runtime.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources/ItemShareFixIcon.png" LogicalName="ItemShareFix.Resources.ItemShareFixIcon.png" />
  </ItemGroup>
</Project>
