using System;
using System.Collections.Generic;
using BepInEx.Configuration;
using RoR2;

namespace ItemShareFix
{
    internal readonly struct MarkerOptionLocalizedText
    {
        public MarkerOptionLocalizedText(string name, string description) { Name = name; Description = description; }
        public string Name { get; }
        public string Description { get; }
    }

    internal static class MarkerRiskOfOptionsLocalization
    {
        public static readonly string[] SupportedLanguages = A("en","fr","it","de","es","ja","ko","pt-BR","ru","zh-CN","tr");
        public static readonly string[] VisibleOptionKeys = A("PersonalMarkersEnabled","MarkerPresentationMode","ShareTemporaryItems","ShowMarkerDistance","MarkerScale","MarkerOpacity","MarkerBackgroundOpacity","ShowMarkerCategoryDiamond","MarkerDetailRows","MarkerCategorySortOrder","MarkerCompactShowCount","EnableOffscreenIndicators","ShowOffscreenDistance","ShowOffscreenTotalCount","OffscreenIndicatorScale","OffscreenIndicatorOpacity","OffscreenEdgePadding","Common","Uncommon","Legendary","Boss","Lunar","Void","Equipment","Command","Neutral","OffscreenIndicator");

        private static readonly Dictionary<string, string[]> OptionNames = new Dictionary<string, string[]>(StringComparer.Ordinal)
        {
            ["PersonalMarkersEnabled"] = A("Enable markers","Enable markers","Enable markers","Enable markers","Enable markers","Enable markers","Enable markers","Enable markers","Enable markers","Enable markers","Enable markers"),
            ["MarkerPresentationMode"] = A("Marker mode","Mode des marqueurs","Modalità indicatori","Markierungsmodus","Modo de marcadores","マーカーモード","마커 모드","Modo dos marcadores","Режим меток","标记模式","İşaretçi modu"),
            ["ShareTemporaryItems"] = A("Share temporary items","Share temporary items","Share temporary items","Share temporary items","Share temporary items","Share temporary items","Share temporary items","Share temporary items","Раздавать временные предметы","Share temporary items","Share temporary items"),
            ["ShowMarkerDistance"] = A("Show distance","Afficher la distance","Mostra distanza","Entfernung anzeigen","Mostrar distancia","距離を表示","거리 표시","Mostrar distância","Показывать расстояние","显示距离","Mesafeyi göster"),
            ["MarkerScale"] = A("Marker scale","Échelle des marqueurs","Scala indicatori","Markierungsgröße","Escala de marcadores","マーカーサイズ","마커 크기","Escala dos marcadores","Масштаб меток","标记缩放","İşaretçi ölçeği"),
            ["MarkerOpacity"] = A("Marker opacity","Opacité des marqueurs","Opacità indicatori","Markierungsdeckkraft","Opacidad de marcadores","マーカー不透明度","마커 불투명도","Opacidade dos marcadores","Прозрачность меток","标记不透明度","İşaretçi opaklığı"),
            ["MarkerBackgroundOpacity"] = A("Background opacity","Opacité du fond","Opacità sfondo","Hintergrunddeckkraft","Opacidad del fondo","背景の不透明度","배경 불투명도","Opacidade do fundo","Прозрачность фона","背景不透明度","Arka plan opaklığı"),
            ["ShowMarkerCategoryDiamond"] = A("Category diamonds","Losanges de catégorie","Diamanti categoria","Kategorie-Rauten","Diamantes de categoría","カテゴリーダイヤ","카테고리 다이아몬드","Diamantes de categoria","Ромбы категорий","类别菱形","Kategori elmasları"),
            ["MarkerDetailRows"] = A("Detailed item rows","Lignes d’objets détaillées","Righe oggetti dettagliate","Detaillierte Gegenstandszeilen","Filas de objetos detalladas","詳細アイテム行","상세 아이템 행","Linhas detalhadas de itens","Строки предметов","详细物品行","Ayrıntılı eşya satırları"),
            ["MarkerCategorySortOrder"] = A("Category sort","Tri des catégories","Ordine categorie","Kategoriereihenfolge","Orden de categorías","カテゴリー順","카테고리 정렬","Ordem das categorias","Сортировка категорий","类别排序","Kategori sırası"),
            ["MarkerCompactShowCount"] = A("Compact counts","Comptes compacts","Conteggi compatti","Kompakte Anzahlen","Conteos compactos","コンパクト個数","컴팩트 개수","Contagens compactas","Счётчики Compact","紧凑计数","Kompakt sayılar"),
            ["EnableOffscreenIndicators"] = A("Off-screen indicators","Indicateurs hors écran","Indicatori fuori schermo","Offscreen-Anzeigen","Indicadores fuera de pantalla","画面外インジケーター","화면 밖 표시기","Indicadores fora da tela","Заэкранные указатели","屏外指示器","Ekran dışı göstergeler"),
            ["ShowOffscreenDistance"] = A("Off-screen distance","Distance hors écran","Distanza fuori schermo","Offscreen-Entfernung","Distancia fuera de pantalla","画面外距離","화면 밖 거리","Distância fora da tela","Заэкранное расстояние","屏外距离","Ekran dışı mesafe"),
            ["ShowOffscreenTotalCount"] = A("Off-screen total","Total hors écran","Totale fuori schermo","Offscreen-Gesamtzahl","Total fuera de pantalla","画面外合計","화면 밖 총계","Total fora da tela","Заэкранное количество","屏外总数","Ekran dışı toplam"),
            ["OffscreenIndicatorScale"] = A("Off-screen scale","Échelle hors écran","Scala fuori schermo","Offscreen-Größe","Escala fuera de pantalla","画面外サイズ","화면 밖 크기","Escala fora da tela","Масштаб заэкранных","屏外缩放","Ekran dışı ölçek"),
            ["OffscreenIndicatorOpacity"] = A("Off-screen opacity","Opacité hors écran","Opacità fuori schermo","Offscreen-Deckkraft","Opacidad fuera de pantalla","画面外不透明度","화면 밖 불투명도","Opacidade fora da tela","Прозрачность заэкранных","屏外不透明度","Ekran dışı opaklık"),
            ["OffscreenEdgePadding"] = A("Edge padding","Marge du bord","Margine bordo","Randabstand","Margen del borde","端の余白","가장자리 여백","Margem da borda","Отступ от края","边缘间距","Kenar boşluğu"),
            ["Common"] = A("Common color","Couleur commune","Colore comune","Gewöhnlich-Farbe","Color común","コモン色","일반 색상","Cor comum","Цвет обычных","普通颜色","Yaygın renk"),
            ["Uncommon"] = A("Uncommon color","Couleur inhabituelle","Colore non comune","Ungewöhnlich-Farbe","Color poco común","アンコモン色","고급 색상","Cor incomum","Цвет необычных","罕见颜色","Sıradışı renk"),
            ["Legendary"] = A("Legendary color","Couleur légendaire","Colore leggendario","Legendär-Farbe","Color legendario","レジェンダリー色","전설 색상","Cor lendária","Цвет легендарных","传奇颜色","Efsanevi renk"),
            ["Boss"] = A("Boss color","Couleur boss","Colore boss","Boss-Farbe","Color de jefe","ボス色","보스 색상","Cor de chefe","Цвет боссовых","首领颜色","Boss rengi"),
            ["Lunar"] = A("Lunar color","Couleur lunaire","Colore lunare","Lunar-Farbe","Color lunar","ルナ色","루나 색상","Cor lunar","Цвет лунных","月球颜色","Ay rengi"),
            ["Void"] = A("Void color","Couleur du Vide","Colore Vuoto","Leeren-Farbe","Color del Vacío","ヴォイド色","공허 색상","Cor do Vazio","Цвет Бездны","虚空颜色","Hiçlik rengi"),
            ["Equipment"] = A("Equipment color","Couleur équipement","Colore equipaggiamento","Ausrüstungsfarbe","Color de equipo","装備色","장비 색상","Cor de equipamento","Цвет снаряжения","装备颜色","Ekipman rengi"),
            ["Command"] = A("Command color","Couleur Commande","Colore Comando","Command-Farbe","Color de Comando","コマンド色","지휘 색상","Cor de Comando","Цвет Command","命令颜色","Komut rengi"),
            ["Neutral"] = A("Neutral color","Couleur neutre","Colore neutro","Neutral-Farbe","Color neutro","ニュートラル色","중립 색상","Cor neutra","Нейтральный цвет","中性颜色","Nötr renk"),
            ["OffscreenIndicator"] = A("Off-screen arrow color","Couleur flèche hors écran","Colore freccia fuori schermo","Offscreen-Pfeilfarbe","Color de flecha fuera de pantalla","画面外矢印色","화면 밖 화살표 색상","Cor da seta fora da tela","Цвет заэкранной стрелки","屏外箭头颜色","Ekran dışı ok rengi"),
        };

        private static readonly string[] MarkerCategoryNames = A("Markers","Marqueurs","Indicatori","Markierungen","Marcadores","マーカー","마커","Marcadores","Метки","标记","İşaretçiler");
        private static readonly string[] GeneralCategoryNames = A("General","General","General","General","General","General","General","General","Общие","General","General");
        private static readonly string[] MarkerColorCategoryNames = A("Marker Colors","Couleurs des marqueurs","Colori indicatori","Markierungsfarben","Colores de marcadores","マーカー色","마커 색상","Cores dos marcadores","Цвета меток","标记颜色","İşaretçi renkleri");

        private static readonly Dictionary<string, string[]> OptionDescriptions = new Dictionary<string, string[]>(StringComparer.Ordinal)
        {
            ["PersonalMarkersEnabled"] = A("Enable ItemShareFix automatic pickup and Command markers. Disable this to keep ItemShareFix fixes active without showing ItemShareFix markers.","Enable ItemShareFix automatic pickup and Command markers. Disable this to keep ItemShareFix fixes active without showing ItemShareFix markers.","Enable ItemShareFix automatic pickup and Command markers. Disable this to keep ItemShareFix fixes active without showing ItemShareFix markers.","Enable ItemShareFix automatic pickup and Command markers. Disable this to keep ItemShareFix fixes active without showing ItemShareFix markers.","Enable ItemShareFix automatic pickup and Command markers. Disable this to keep ItemShareFix fixes active without showing ItemShareFix markers.","Enable ItemShareFix automatic pickup and Command markers. Disable this to keep ItemShareFix fixes active without showing ItemShareFix markers.","Enable ItemShareFix automatic pickup and Command markers. Disable this to keep ItemShareFix fixes active without showing ItemShareFix markers.","Enable ItemShareFix automatic pickup and Command markers. Disable this to keep ItemShareFix fixes active without showing ItemShareFix markers.","Enable ItemShareFix automatic pickup and Command markers. Disable this to keep ItemShareFix fixes active without showing ItemShareFix markers.","Enable ItemShareFix automatic pickup and Command markers. Disable this to keep ItemShareFix fixes active without showing ItemShareFix markers.","Enable ItemShareFix automatic pickup and Command markers. Disable this to keep ItemShareFix fixes active without showing ItemShareFix markers."),
            ["ShareTemporaryItems"] = A("Share temporary item pickups through ItemShare. Disable this to give temporary pickups vanilla first-come-first-served behavior instead of ItemShare distribution.","Share temporary item pickups through ItemShare. Disable this to give temporary pickups vanilla first-come-first-served behavior instead of ItemShare distribution.","Share temporary item pickups through ItemShare. Disable this to give temporary pickups vanilla first-come-first-served behavior instead of ItemShare distribution.","Share temporary item pickups through ItemShare. Disable this to give temporary pickups vanilla first-come-first-served behavior instead of ItemShare distribution.","Share temporary item pickups through ItemShare. Disable this to give temporary pickups vanilla first-come-first-served behavior instead of ItemShare distribution.","Share temporary item pickups through ItemShare. Disable this to give temporary pickups vanilla first-come-first-served behavior instead of ItemShare distribution.","Share temporary item pickups through ItemShare. Disable this to give temporary pickups vanilla first-come-first-served behavior instead of ItemShare distribution.","Share temporary item pickups through ItemShare. Disable this to give temporary pickups vanilla first-come-first-served behavior instead of ItemShare distribution.","Раздавать временные предметы через ItemShare. Если выключено, временные предметы получают ванильное поведение: предмет достаётся первому подобравшему игроку без распределения ItemShare.","Share temporary item pickups through ItemShare. Disable this to give temporary pickups vanilla first-come-first-served behavior instead of ItemShare distribution.","Share temporary item pickups through ItemShare. Disable this to give temporary pickups vanilla first-come-first-served behavior instead of ItemShare distribution."),
            ["MarkerPresentationMode"] = A("Choose Detailed exact-item rows or Compact category-diamond summaries.","Choisit les lignes d’objets exactes en mode Détaillé ou les résumés par losanges en mode Compact.","Sceglie righe oggetto esatte in Dettagliato o riepiloghi a diamanti in Compatto.","Wählt exakte Gegenstandszeilen in Detailliert oder Kategorie-Rauten in Kompakt.","Elige filas de objetos exactos en Detallado o resúmenes de diamantes en Compacto.","詳細では正確なアイテム行、コンパクトではカテゴリーダイヤの要約を表示します。","상세에서는 정확한 아이템 행을, 컴팩트에서는 카테고리 다이아몬드 요약을 표시합니다.","Escolhe linhas exatas de itens em Detalhado ou resumos por diamantes em Compacto.","Выбирает точные строки предметов в подробном режиме или сводку ромбами категорий в компактном.","详细模式显示精确物品行，紧凑模式显示类别菱形摘要。","Ayrıntılı modda tam eşya satırlarını, Kompakt modda kategori elması özetlerini seçer."),
            ["ShowMarkerDistance"] = A("Show the world distance under in-FOV marker content.","Affiche la distance sous le contenu des marqueurs visibles.","Mostra la distanza sotto il contenuto dei marker visibili.","Zeigt die Weltdistanz unter sichtbaren Markierungen.","Muestra la distancia bajo el contenido de marcadores visibles.","画面内マーカーの内容の下に距離を表示します。","화면 안 마커 내용 아래에 거리를 표시합니다.","Mostra a distância abaixo do conteúdo dos marcadores visíveis.","Показывает расстояние под содержимым метки в поле зрения.","在视野内标记内容下方显示世界距离。","Görüş içindeki işaretçi içeriğinin altında dünya mesafesini gösterir."),
            ["MarkerScale"] = A("Scale marker UI only; world membership and clustering are unchanged.","Ajuste uniquement l’échelle de l’interface des marqueurs sans modifier le regroupement.","Ridimensiona solo l’interfaccia dei marker senza cambiare il raggruppamento.","Skaliert nur die Marker-UI; Weltzuordnung und Cluster bleiben unverändert.","Escala solo la interfaz de marcadores; no cambia la agrupación.","マーカーUIのみを拡大縮小し、ワールド所属やクラスタは変更しません。","마커 UI만 크기 조절하며 월드 멤버십과 클러스터링은 바뀌지 않습니다.","Ajusta apenas a interface dos marcadores; associação e agrupamento não mudam.","Меняет только масштаб интерфейса меток, не затрагивая состав и кластеризацию.","仅缩放标记界面，不改变世界成员关系或聚类。","Yalnızca işaretçi arayüzünü ölçekler; dünya üyeliği ve kümeler değişmez."),
            ["MarkerOpacity"] = A("Set the opacity of on-screen world markers.","Règle l’opacité des marqueurs du monde à l’écran.","Imposta l’opacità dei marker del mondo sullo schermo.","Legt die Deckkraft der sichtbaren Weltmarkierungen fest.","Ajusta la opacidad de los marcadores del mundo en pantalla.","画面内ワールドマーカーの不透明度を設定します。","화면 내 월드 마커의 불투명도를 설정합니다.","Define a opacidade dos marcadores do mundo na tela.","Задаёт непрозрачность экранных мировых меток.","设置屏幕内世界标记的不透明度。","Ekrandaki dünya işaretçilerinin opaklığını ayarlar."),
            ["MarkerBackgroundOpacity"] = A("Set marker card background opacity; zero keeps the transparent HUD style.","Règle l’opacité du fond des cartes; zéro conserve le style transparent.","Imposta l’opacità dello sfondo; zero mantiene lo stile trasparente.","Legt die Karten-Hintergrunddeckkraft fest; null behält den transparenten Stil.","Ajusta la opacidad del fondo; cero mantiene el estilo transparente.","マーカーカード背景の不透明度を設定し、0で透明スタイルを維持します。","마커 카드 배경 불투명도를 설정하며 0은 투명 스타일을 유지합니다.","Define a opacidade do fundo; zero mantém o estilo transparente.","Задаёт непрозрачность фона карточки; ноль сохраняет прозрачный стиль.","设置标记卡片背景不透明度；0 保持透明样式。","Kart arka plan opaklığını ayarlar; sıfır saydam HUD stilini korur."),
            ["ShowMarkerCategoryDiamond"] = A("Show or hide category diamonds without changing marker text or membership.","Affiche ou masque les losanges sans modifier le texte ni l’appartenance.","Mostra o nasconde i diamanti senza cambiare testo o appartenenza.","Blendet Kategorie-Rauten ein/aus, ohne Text oder Zugehörigkeit zu ändern.","Muestra u oculta diamantes sin cambiar texto ni pertenencia.","テキストや所属を変えずにカテゴリーダイヤを表示・非表示にします。","텍스트나 멤버십을 바꾸지 않고 카테고리 다이아몬드를 표시하거나 숨깁니다.","Mostra ou oculta diamantes sem alterar texto ou associação.","Показывает или скрывает ромбы категорий, не меняя текст и состав метки.","显示或隐藏类别菱形，不改变文本或成员关系。","Metin veya üyeliği değiştirmeden kategori elmaslarını gösterir ya da gizler."),
            ["MarkerDetailRows"] = A("Limit visible distinct item types in ordinary Detailed markers before the localized overflow row.","Limite les types d’objets distincts visibles avant la ligne de débordement localisée.","Limita i tipi di oggetti distinti visibili prima della riga di overflow localizzata.","Begrenzt sichtbare unterschiedliche Gegenstandstypen vor der lokalisierten Überlaufzeile.","Limita los tipos de objetos distintos visibles antes de la fila de desbordamiento localizada.","通常の詳細マーカーで表示する異なるアイテム種類数を、ローカライズ済み省略行の前まで制限します。","일반 상세 마커에서 현지화된 초과 행 전까지 표시할 서로 다른 아이템 종류 수를 제한합니다.","Limita os tipos distintos visíveis antes da linha localizada de excedentes.","Ограничивает число видимых различных типов предметов до локализованной строки переполнения.","限制普通详细标记中可见的不同物品类型数量，超出部分显示本地化省略行。","Normal Ayrıntılı işaretçilerde yerelleştirilmiş taşma satırından önce görünen farklı eşya türlerini sınırlar."),
            ["MarkerCategorySortOrder"] = A("Choose category display order; LowToHigh is the exact reverse of HighToLow.","Choisit l’ordre des catégories; Faible→Élevé inverse exactement Élevé→Faible.","Sceglie l’ordine categorie; Basso→Alto è l’esatto inverso di Alto→Basso.","Wählt die Kategorienreihenfolge; Niedrig→Hoch ist die exakte Umkehrung.","Elige el orden de categorías; Bajo→Alto es el inverso exacto de Alto→Bajo.","カテゴリ表示順を選びます。低→高は高→低の完全な逆順です。","카테고리 표시 순서를 선택합니다. 낮음→높음은 높음→낮음의 정확한 역순입니다.","Escolhe a ordem das categorias; Baixo→Alto é o inverso exato de Alto→Baixo.","Выбирает порядок категорий; «от низкого к высокому» — точный обратный порядок.","选择类别显示顺序；从低到高是从高到低的完全反序。","Kategori sırasını seçer; Düşükten yükseğe, Yüksekten düşüğün tam tersidir."),
            ["MarkerCompactShowCount"] = A("Show each category subtotal beside its Compact diamond; no overall total is added.","Affiche le sous-total de chaque catégorie près de son losange Compact, sans total général.","Mostra il subtotale di ogni categoria accanto al diamante Compatto, senza totale generale.","Zeigt jede Kategorie-Zwischensumme an ihrer Kompakt-Raute ohne Gesamtsumme.","Muestra el subtotal de cada categoría junto a su diamante Compacto, sin total general.","各コンパクトダイヤの横にカテゴリ小計を表示し、全体合計は追加しません。","각 컴팩트 다이아몬드 옆에 카테고리 소계를 표시하며 전체 합계는 추가하지 않습니다.","Mostra o subtotal de cada categoria junto ao diamante Compacto, sem total geral.","Показывает счётчик каждой категории возле её ромба Compact без общего total.","在每个紧凑类别菱形旁显示小计，不添加总计。","Her Kompakt kategori elmasının yanında ara toplamı gösterir; genel toplam eklemez."),
            ["EnableOffscreenIndicators"] = A("Show one restrained directional arrow per occupied broad off-screen direction.","Affiche une flèche directionnelle limitée par grande direction hors écran occupée.","Mostra una freccia direzionale contenuta per ogni ampia direzione fuori schermo occupata.","Zeigt einen zurückhaltenden Richtungspfeil pro belegter grober Offscreen-Richtung.","Muestra una flecha direccional contenida por cada dirección amplia fuera de pantalla ocupada.","占有されている大まかな画面外方向ごとに、抑制された矢印を1つ表示します。","점유된 넓은 화면 밖 방향마다 절제된 방향 화살표 하나를 표시합니다.","Mostra uma seta direcional discreta por direção ampla ocupada fora da tela.","Показывает по одной сдержанной стрелке на занятое широкое заэкранное направление.","每个有内容的宽泛屏外方向显示一个克制的方向箭头。","Dolu her geniş ekran dışı yön için tek, ölçülü bir yön oku gösterir."),
            ["ShowOffscreenDistance"] = A("Show the nearest represented pending distance on each off-screen arrow.","Affiche sur chaque flèche la distance du pending représenté le plus proche.","Mostra su ogni freccia la distanza pending rappresentata più vicina.","Zeigt an jedem Pfeil die nächste repräsentierte ausstehende Entfernung.","Muestra en cada flecha la distancia pendiente representada más cercana.","各画面外矢印に、代表される保留対象の最短距離を表示します。","각 화면 밖 화살표에 대표된 보류 대상 중 가장 가까운 거리를 표시합니다.","Mostra em cada seta a menor distância pendente representada.","Показывает на каждой стрелке ближайшее расстояние среди представленных pending-целей.","在每个屏外箭头上显示所代表待处理目标中的最近距离。","Her ekran dışı okta temsil edilen en yakın bekleyen mesafeyi gösterir."),
            ["ShowOffscreenTotalCount"] = A("Optionally show the represented sector total once on each off-screen arrow.","Affiche facultativement une fois le total du secteur représenté sur chaque flèche.","Mostra facoltativamente una volta il totale del settore rappresentato su ogni freccia.","Zeigt optional einmal die repräsentierte Sektorsumme an jedem Pfeil.","Muestra opcionalmente una vez el total del sector representado en cada flecha.","各画面外矢印に、そのセクターの代表合計数を任意で1回表示します。","각 화면 밖 화살표에 대표 섹터 총수를 선택적으로 한 번 표시합니다.","Mostra opcionalmente uma vez o total do setor representado em cada seta.","Опционально показывает один общий счётчик представленного сектора на каждой стрелке.","可选地在每个屏外箭头上仅显示一次所代表扇区的总数。","Her ekran dışı okta temsil edilen sektör toplamını isteğe bağlı olarak bir kez gösterir."),
            ["OffscreenIndicatorScale"] = A("Scale off-screen directional arrows only; directional ownership is unchanged.","Ajuste uniquement l’échelle des flèches hors écran sans changer leur propriété directionnelle.","Ridimensiona solo le frecce fuori schermo senza cambiarne la proprietà direzionale.","Skaliert nur Offscreen-Pfeile; die Richtungszuordnung bleibt unverändert.","Escala solo las flechas fuera de pantalla; la propiedad direccional no cambia.","画面外方向矢印のみを拡大縮小し、方向所有は変更しません。","화면 밖 방향 화살표만 크기 조절하며 방향 소유권은 바뀌지 않습니다.","Ajusta apenas as setas fora da tela; a associação direcional não muda.","Меняет только масштаб заэкранных стрелок, не затрагивая directional ownership.","仅缩放屏外方向箭头，不改变方向归属。","Yalnızca ekran dışı yön oklarını ölçekler; yön sahipliği değişmez."),
            ["OffscreenIndicatorOpacity"] = A("Set the opacity of off-screen directional arrows.","Règle l’opacité des flèches directionnelles hors écran.","Imposta l’opacità delle frecce direzionali fuori schermo.","Legt die Deckkraft der Offscreen-Richtungspfeile fest.","Ajusta la opacidad de las flechas direccionales fuera de pantalla.","画面外方向矢印の不透明度を設定します。","화면 밖 방향 화살표의 불투명도를 설정합니다.","Define a opacidade das setas direcionais fora da tela.","Задаёт непрозрачность заэкранных направляющих стрелок.","设置屏外方向箭头的不透明度。","Ekran dışı yön oklarının opaklığını ayarlar."),
            ["OffscreenEdgePadding"] = A("Keep off-screen arrows this many pixels away from the screen edge.","Maintient les flèches hors écran à cette distance en pixels du bord.","Mantiene le frecce fuori schermo a questa distanza in pixel dal bordo.","Hält Offscreen-Pfeile um diese Pixelzahl vom Bildschirmrand entfernt.","Mantiene las flechas fuera de pantalla a esta distancia en píxeles del borde.","画面外矢印を画面端から指定ピクセル分内側に保ちます。","화면 밖 화살표를 화면 가장자리에서 지정 픽셀만큼 안쪽에 유지합니다.","Mantém as setas fora da tela a esta distância em pixels da borda.","Держит заэкранные стрелки на указанном расстоянии в пикселях от края экрана.","使屏外箭头与屏幕边缘保持指定像素距离。","Ekran dışı okları ekran kenarından bu kadar piksel uzakta tutar."),
            ["Common"] = A("Set the color used for common/white item markers.","Définit la couleur utilisée pour les marqueurs d’objets communs/blancs.","Imposta il colore usato per marker oggetti comuni/bianchi.","Legt die Farbe für gewöhnliche/weiße Gegenstandsmarker fest.","Ajusta el color usado para marcadores de objetos comunes/blancos.","コモン/白アイテムのマーカーに使用する色を設定します。","일반/흰색 아이템 마커에 사용할 색상을 설정합니다.","Define a cor usada para marcadores de itens comuns/brancos.","Задаёт цвет для метки обычных/белых предметов.","设置用于普通/白色物品标记的颜色。","yaygın/beyaz eşya işaretçileri için kullanılan rengi ayarlar."),
            ["Uncommon"] = A("Set the color used for uncommon/green item markers.","Définit la couleur utilisée pour les marqueurs d’objets inhabituels/verts.","Imposta il colore usato per marker oggetti non comuni/verdi.","Legt die Farbe für ungewöhnliche/grüne Gegenstandsmarker fest.","Ajusta el color usado para marcadores de objetos poco comunes/verdes.","アンコモン/緑アイテムのマーカーに使用する色を設定します。","고급/초록 아이템 마커에 사용할 색상을 설정합니다.","Define a cor usada para marcadores de itens incomuns/verdes.","Задаёт цвет для метки необычных/зелёных предметов.","设置用于罕见/绿色物品标记的颜色。","sıradışı/yeşil eşya işaretçileri için kullanılan rengi ayarlar."),
            ["Legendary"] = A("Set the color used for legendary/red item markers.","Définit la couleur utilisée pour les marqueurs d’objets légendaires/rouges.","Imposta il colore usato per marker oggetti leggendari/rossi.","Legt die Farbe für legendäre/rote Gegenstandsmarker fest.","Ajusta el color usado para marcadores de objetos legendarios/rojos.","レジェンダリー/赤アイテムのマーカーに使用する色を設定します。","전설/빨간 아이템 마커에 사용할 색상을 설정합니다.","Define a cor usada para marcadores de itens lendários/vermelhos.","Задаёт цвет для метки легендарных/красных предметов.","设置用于传奇/红色物品标记的颜色。","efsanevi/kırmızı eşya işaretçileri için kullanılan rengi ayarlar."),
            ["Boss"] = A("Set the color used for boss item markers.","Définit la couleur utilisée pour les marqueurs d’objets de boss.","Imposta il colore usato per marker oggetti boss.","Legt die Farbe für Boss-Gegenstandsmarker fest.","Ajusta el color usado para marcadores de objetos de jefe.","ボスアイテムのマーカーに使用する色を設定します。","보스 아이템 마커에 사용할 색상을 설정합니다.","Define a cor usada para marcadores de itens de chefe.","Задаёт цвет для метки боссовых предметов.","设置用于首领物品标记的颜色。","boss eşyası işaretçileri için kullanılan rengi ayarlar."),
            ["Lunar"] = A("Set the color used for lunar and lunar-equipment markers.","Définit la couleur utilisée pour les marqueurs lunaires et d’équipement lunaire.","Imposta il colore usato per marker lunari e equipaggiamento lunare.","Legt die Farbe für Lunar- und Lunar-Ausrüstungsmarker fest.","Ajusta el color usado para marcadores lunares y de equipo lunar.","ルナおよびルナ装備マーカーに使用する色を設定します。","루나 및 루나 장비 마커에 사용할 색상을 설정합니다.","Define a cor usada para marcadores lunares e de equipamento lunar.","Задаёт цвет для метки лунных предметов и лунного снаряжения.","设置用于月球物品和月球装备标记的颜色。","ay ve ay ekipmanı işaretçileri için kullanılan rengi ayarlar."),
            ["Void"] = A("Set the color used for Void item markers.","Définit la couleur utilisée pour les marqueurs d’objets du Vide.","Imposta il colore usato per marker oggetti del Vuoto.","Legt die Farbe für Leeren-Gegenstandsmarker fest.","Ajusta el color usado para marcadores de objetos del Vacío.","ヴォイドアイテムのマーカーに使用する色を設定します。","공허 아이템 마커에 사용할 색상을 설정합니다.","Define a cor usada para marcadores de itens do Vazio.","Задаёт цвет для метки предметов Бездны.","设置用于虚空物品标记的颜色。","Hiçlik eşyası işaretçileri için kullanılan rengi ayarlar."),
            ["Equipment"] = A("Set the color used for equipment markers.","Définit la couleur utilisée pour les marqueurs d’équipement.","Imposta il colore usato per marker equipaggiamento.","Legt die Farbe für Ausrüstungsmarker fest.","Ajusta el color usado para marcadores de equipo.","装備マーカーに使用する色を設定します。","장비 마커에 사용할 색상을 설정합니다.","Define a cor usada para marcadores de equipamento.","Задаёт цвет для метки снаряжения.","设置用于装备标记的颜色。","ekipman işaretçileri için kullanılan rengi ayarlar."),
            ["Command"] = A("Set the color used for Artifact of Command unresolved-choice markers.","Définit la couleur utilisée pour les marqueurs de choix non résolus de l’Artéfact de Commande.","Imposta il colore usato per marker di scelta irrisolta dell’Artefatto del Comando.","Legt die Farbe für Marker für ungelöste Artefakt-des-Kommandos-Auswahlen fest.","Ajusta el color usado para marcadores de elección sin resolver del Artefacto de Comando.","コマンドのアーティファクト未解決選択マーカーに使用する色を設定します。","지휘의 유물 미결 선택 마커에 사용할 색상을 설정합니다.","Define a cor usada para marcadores de escolha não resolvida do Artefato do Comando.","Задаёт цвет для метки незавершённого выбора Артефакта Command.","设置用于命令神器未解决选择标记的颜色。","Komut Eseri çözülmemiş seçim işaretçileri için kullanılan rengi ayarlar."),
            ["Neutral"] = A("Set the color used for mixed, unknown, and other markers.","Définit la couleur utilisée pour les marqueurs mixtes, inconnus et autres.","Imposta il colore usato per marker misti, sconosciuti e altri.","Legt die Farbe für gemischte, unbekannte und sonstige Marker fest.","Ajusta el color usado para marcadores mixtos, desconocidos y otros.","混合・不明・その他のマーカーに使用する色を設定します。","혼합/알 수 없음/기타 마커에 사용할 색상을 설정합니다.","Define a cor usada para marcadores mistos, desconhecidos e outros.","Задаёт цвет для смешанные, неизвестные и прочие метки.","设置用于混合、未知及其他标记的颜色。","karışık, bilinmeyen ve diğer işaretçiler için kullanılan rengi ayarlar."),
            ["OffscreenIndicator"] = A("Set the color used for off-screen directional arrows.","Définit la couleur utilisée pour les flèches directionnelles hors écran.","Imposta il colore usato per frecce direzionali fuori schermo.","Legt die Farbe für Offscreen-Richtungspfeile fest.","Ajusta el color usado para flechas direccionales fuera de pantalla.","画面外方向矢印に使用する色を設定します。","화면 밖 방향 화살표에 사용할 색상을 설정합니다.","Define a cor usada para setas direcionais fora da tela.","Задаёт цвет для заэкранные направляющие стрелки.","设置用于屏外方向箭头的颜色。","ekran dışı yön okları için kullanılan rengi ayarlar."),
        };

        private static readonly string[][] PresentationChoices =
        {
            A("Detailed","Détaillé","Dettagliato","Detailliert","Detallado","詳細","상세","Detalhado","Подробный","详细","Ayrıntılı"),
            A("Compact","Compact","Compatto","Kompakt","Compacto","コンパクト","컴팩트","Compacto","Компактный","紧凑","Kompakt"),
        };

        private static readonly string[][] SortOrderChoices =
        {
            A("High to low","Élevé vers faible","Alto → basso","Hoch nach niedrig","Alto a bajo","高→低","높음→낮음","Alto para baixo","От высокого к низкому","从高到低","Yüksekten düşüğe"),
            A("Low to high","Faible vers élevé","Basso → alto","Niedrig nach hoch","Bajo a alto","低→高","낮음→높음","Baixo para alto","От низкого к высокому","从低到高","Düşükten yükseğe"),
        };

        public static MarkerOptionLocalizedText Resolve(ConfigEntryBase entry)
            => ResolveForLanguage(entry.Definition.Key, ResolveLanguageIndex());

        public static string ResolveCategory(ConfigEntryBase entry)
            => string.Equals(entry.Definition.Key, "ShareTemporaryItems", StringComparison.Ordinal)
                ? GeneralCategoryNames[NormalizeLanguageIndex(ResolveLanguageIndex())]
                : ResolveCategoryForLanguage(entry.Definition.Section, ResolveLanguageIndex());

        internal static string ResolveCategoryForLanguage(string section, int languageIndex)
        {
            var i = NormalizeLanguageIndex(languageIndex);
            return string.Equals(section, "Marker Colors", StringComparison.Ordinal) ? MarkerColorCategoryNames[i] : MarkerCategoryNames[i];
        }

        internal static string CurrentLanguageKey()
            => NormalizeLanguageKey(Language.currentLanguageName);

        internal static MarkerOptionLocalizedText ResolveForLanguage(string key, int languageIndex)
        {
            var i = NormalizeLanguageIndex(languageIndex);
            if (!OptionNames.TryGetValue(key, out var names)) names = A(key,key,key,key,key,key,key,key,key,key,key);
            if (!OptionDescriptions.TryGetValue(key, out var descriptions))
                descriptions = A("ItemShareFix marker option.","Option de marqueur ItemShareFix.","Opzione marker ItemShareFix.","ItemShareFix-Markeroption.","Opción de marcador ItemShareFix.","ItemShareFix マーカー設定。","ItemShareFix 마커 옵션.","Opção de marcador ItemShareFix.","Параметр меток ItemShareFix.","ItemShareFix 标记选项。","ItemShareFix işaretçi seçeneği.");
            return new MarkerOptionLocalizedText(names[i], descriptions[i]);
        }

        public static string[] PresentationModeChoices() => ChoiceForLanguage(PresentationChoices, ResolveLanguageIndex());
        public static string[] SortChoices() => ChoiceForLanguage(SortOrderChoices, ResolveLanguageIndex());

        private static string[] ChoiceForLanguage(string[][] table, int languageIndex)
        {
            var i = NormalizeLanguageIndex(languageIndex);
            var result = new string[table.Length];
            for (var row = 0; row < table.Length; row++) result[row] = table[row][i];
            return result;
        }

        private static int NormalizeLanguageIndex(int index) => index >= 0 && index < SupportedLanguages.Length ? index : 0;

        private static int ResolveLanguageIndex()
            => ResolveLanguageIndexForName(Language.currentLanguageName);

        internal static int ResolveLanguageIndexForName(string? raw)
        {
            var key = NormalizeLanguageKey(raw);
            if (key.Contains("french") || key.StartsWith("fr")) return 1;
            if (key.Contains("italian") || key.StartsWith("it")) return 2;
            if (key.Contains("german") || key.StartsWith("de")) return 3;
            if (key.Contains("spanish") || key.StartsWith("es")) return 4;
            if (key.Contains("japanese") || key.StartsWith("ja")) return 5;
            if (key.Contains("korean") || key.StartsWith("ko")) return 6;
            if (key.Contains("portuguese") || key.StartsWith("pt")) return 7;
            if (key.Contains("russian") || key.StartsWith("ru")) return 8;
            if (key.Contains("chinese") || key.StartsWith("zh")) return 9;
            if (key.Contains("turkish") || key.StartsWith("tr")) return 10;
            return 0;
        }

        private static string NormalizeLanguageKey(string? raw)
            => (raw ?? string.Empty).Trim().ToLowerInvariant();

        private static string[] A(params string[] values) => values;
    }
}
